name: docker

on:
  - push

env:
  ALLURE_ENDPOINT: https://demo.testops.cloud
  ALLURE_TOKEN: ${{ secrets.ALLURE_TOKEN }}
  ALLURE_PROJECT_ID: ${{ secrets.ALLURE_PROJECT_ID }}

jobs:
  test:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - uses: actions/checkout@v3
      - uses: allure-framework/setup-allurectl@v1
      - name: Prepare env file for Docker container
        run: echo "ALLURE_CI_ENV=$(allurectl ci env --encode)" >> $GITHUB_ENV
      - name: Build docker container
        run: docker build -t uploader:latest .
      - name: Run autotests in docker allurectl
        run: |
          docker run --volume "$(pwd)":/github/workspace \
                     --workdir=/github/workspace \
                     -e ALLURE_CI_ENV=${ALLURE_CI_ENV} \
                     uploader:latest
